routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
	return view('welcome');
});

Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('home', 'HomeController@index')->name('admin.home.index');
    Route::resource('articles', 'ArticleController', ['as' => 'admin'])->except(['show']);
});

Route::namespace('App')->prefix('home')->group(function () {
    Route::get('', 'HomeController@index')->name('app.home.index');
    Route::resource('articles', 'ArticleController', ['as' => 'app'])->only(['index', 'show']);
	Auth::routes();
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
    	'title', 'slug', 'body', 'user_id'
    ];

    /**
     * Use slug instead of id.
     */
    public function getRouteKeyName() 
    {
        return 'slug';
    }

    /**
     * An article is created by an user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
    	return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * A user can have many roles.
     * 
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    /**
     * Check multiple roles.
     *
     * @param array $roles
     */
    public function hasRoles(array $roles)
    {
        return $this->roles->whereIn('name', $roles)->first();
    }

    /**
     * Check user role.
     *
     * @param $role
     */
    public function role($role)
    {
        return $this->roles->where('name', $role)->first();
    }

    /**
     * Check if user is an administrator.
     */
    public function getAdministratorAttribute()
    {
        return $this->role('administrator');
    }

    /**
     * A user can have many articles.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function articles()
    {
        return $this->hasMany(Article::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Article;

class ArticleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('role:administrator');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::orderBy('updated_at', 'desc')
        ->with('user')
        ->paginate(10);
        
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        request()->validate([
            'title' => 'required',
            'slug' => 'required|alpha_dash|unique:articles',
            'body' => 'required',
        ]);

        request()->request->add([
            'user_id' => auth()->user()->id
        ]);

        Article::create(request()->all());
        return redirect()->route('admin.articles.index')->withSuccess('Article Created.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(Article $article)
    {
        request()->validate([
            'title' => 'required',
            'slug' => 'required|alpha_dash|unique:articles,slug,'.$article->id,
            'body' => 'required',
        ]);

        $article->update(request()->all());
        return redirect()->route('admin.articles.index')->withSuccess('Article Updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('admin.articles.index')->withSuccess('Article Deleted.');
    }
}

app/Http/Controllers/App/ArticleController.php
<?php

namespace App\Http\Controllers\App;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Article;

class ArticleController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::orderBy('updated_at', 'desc')
        ->with('user')
        ->paginate(10);
        
        return view('app.articles.index', compact('articles'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view('app.articles.show', compact('article'));
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.templates.default')

@section('navigation')
    @include('admin.templates.partials.navigation')
@endsection

@section('content')
    <h2>Create Article</h2>
	@include('admin.templates.partials.messages.errors')
	<form action="{{ route('admin.articles.store') }}" method="POST">
		{{ csrf_field() }}
		<fieldset>
			<legend>Title</legend>
			<input name="title" type="text" value="{{ old('title') ? old('title') : '' }}">
		</fieldset>
		<fieldset>
			<legend>Slug</legend>
			<input name="slug" type="text" value="{{ old('slug') ? old('slug') : '' }}">
		</fieldset>
		<fieldset>
			<legend>Body</legend>
			<textarea name="body" cols="30" rows="10">{{ old('body') ? old('body') : '' }}</textarea>
		</fieldset>
		<button type="submit">Submit</button>
	</form>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.templates.default')

@section('navigation')
    @include('admin.templates.partials.navigation')
@endsection

@section('content')
    <h2>Edit Article</h2>
	@include('admin.templates.partials.messages.errors')
	<form action="{{ route('admin.articles.update', $article->slug) }}" method="POST">
		{{ csrf_field() }}
        {{ method_field('PATCH') }}
		<fieldset>
			<legend>Title</legend>
			<input name="title" type="text" value="{{ $article->title ? $article->title : '' }}">
		</fieldset>
		<fieldset>
			<legend>Slug</legend>
			<input name="slug" type="text" value="{{ $article->slug ? $article->slug : '' }}">
		</fieldset>
		<fieldset>
			<legend>Body</legend>
			<textarea name="body" cols="30" rows="10">{{ $article->body ? $article->body : '' }}</textarea>
		</fieldset>
		<button type="submit">Submit</button>
	</form>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.templates.default')

@section('navigation')
    @include('admin.templates.partials.navigation')
@endsection

@section('content')
@if ($articles->hasMorePages() or $articles->lastItem())
	{{ $articles->links() }}
@endif
	<h2>Articles</h2>
	@include('admin.templates.partials.messages.success')
	<table>
	    <thead>
	      <tr>
	        <th>ID</th>
	        <th>Title</th>
	        <th>By</th>
	        <th>Actions</th>
	      </tr>
	    </thead>
	    <tbody>
	       @forelse($articles as $article)
					<tr>
			        <td>{{ $article->id }}</td>
			        <td>{{ $article->title }}</td>
			        <td>{{ ucfirst($article->user->name) }}</td>
			        <td>
			        	<a href="{{ route('admin.articles.edit', $article->slug) }}">edit</a>
			        </td>
			        <td>
			        	<form action="{{ route('admin.articles.destroy', $article->slug) }}" method="POST">
			        		{{ method_field('DELETE') }}
						    {{ csrf_field() }}
						    <button type="submit">delete</button>
						</form>
			        </td>
	      		</tr>
    		@empty
    			<tr>
    				<td colspan="4">
    					No articles posted.
    				</td>
    			</tr>
    		@endforelse
	    </tbody>
		</table>
@endsection

resources/views/admin/templates/partials/navigation.blade.php
<fieldset>
	@guest
	    <a href="{{ route('login') }}">Login</a>
	    <a href="{{ route('register') }}">Register</a>
	@else
		<legend>Welcome {{ auth()->user()->name }}</legend>
	    @if(auth()->user()->administrator)
	        <a href="{{ route('admin.home.index') }}">Admin Panel</a>
	    @endif
    	<a href="{{ route('logout') }}"
            onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
            Logout
        </a>
    	<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
	@endguest
</fieldset>

<fieldset>
	<legend>Navigation</legend>
	<a href="{{ route('app.home.index') }}" target="_blank">App Home</a>
	<a href="{{ route('admin.articles.create') }}">Create Article</a>
	<a href="{{ route('admin.articles.index') }}">View Articles</a>
</fieldset>

resources/views/app/articles/index.blade.php
@extends('app.templates.default')

@section('navigation')
    @include('app.templates.partials.navigation')
@endsection

@section('content')
    <div class="col-md-9">
        @if ($articles->hasMorePages() or $articles->lastItem())
            {{ $articles->links() }}
        @endif

        @foreach($articles as $article)
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ route('app.articles.show', $article->slug) }}">{{ $article->title }}</a>
                </div>
                <div class="panel-body">
                    {!! $article->body !!}
                </div>
                <div class="panel-footer">
                    Created By: {{ ucfirst($article->user->name) }}
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/app/articles/show.blade.php
@extends('app.templates.default')

@section('navigation')
    @include('app.templates.partials.navigation')
@endsection

@section('content')
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">{{ $article->title }}</div>
            <div class="panel-body">
                {!! $article->body !!}
            </div>
            <div class="panel-footer">
                Created By: {{ ucfirst($article->user->name) }}
            </div>
        </div>
    </div>
@endsection

resources/views/app/templates/partials/navigation.blade.php
<fieldset>
	@guest
	    <a href="{{ route('login') }}">Login</a>
	    <a href="{{ route('register') }}">Register</a>
	@else
		<legend>Welcome {{ auth()->user()->name }}</legend>
 		@if(auth()->user()->administrator)
	        <a href="{{ route('admin.home.index') }}">Admin Panel</a>
	    @endif
    	<a href="{{ route('logout') }}"
            onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
            Logout
        </a>
    	<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
	@endguest
</fieldset>

<fieldset>
	<legend>Navigation</legend>
	<a href="{{ route('app.home.index') }}">Home</a>
	<a href="{{ route('app.articles.index') }}">Articles</a>
</fieldset>